# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

autoSwitchAppearance = true 
colorScheme = "ocean" 
defaultAppearance = "dark" # valid options: light or dark
showAppearanceSwitcher = true 

enableCodeCopy = true
enableSearch = true

mainSections = ["posts", "bytes"]
# robots = ""
showScrollToTop = true

[homepage]
layout = "page" # valid options: page, profile, custom
showRecent = true 

[article]
showAuthor = true
showBreadcrumbs = false
showDate = true
showDateUpdated = false
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/username/repo/"
editAppendPath = true
invertPagination = false
sharingLinks = ["twitter", "reddit", "linkedin", "email"]
showHeadingAnchors = true
showPagination = true
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showWordCount = false

[list]
groupByYear = true
showBreadcrumbs = false
showSummary = false
showTableOfContents = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
